create table expense (id uuid not null, time_creation timestamp(6), time_removed timestamp(6), time_update timestamp(6), amount numeric(8,2) not null, date_register date not null, description varchar(100) not null, buy_method varchar(255), id_user uuid not null, id_wallet uuid not null, primary key (id));
create table income (id uuid not null, time_creation timestamp(6), time_removed timestamp(6), time_update timestamp(6), amount numeric(8,2) not null, date_register date not null, description varchar(100) not null, id_user uuid not null, id_wallet uuid not null, primary key (id));
create table usr (id uuid not null, time_creation timestamp(6), time_removed timestamp(6), time_update timestamp(6), email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id));
create table wallet (id uuid not null, time_creation timestamp(6), time_removed timestamp(6), time_update timestamp(6), month smallint not null, year integer not null, id_user_collaborator uuid, id_user_owner uuid not null, primary key (id));
alter table if exists usr add constraint UK_g9l96r670qkidthshajdtxrqf unique (email);
alter table if exists expense add constraint FKobusl0kfbkmsgeg2orbvlkyg4 foreign key (id_user) references usr;
alter table if exists expense add constraint FKcl45ciwbawegqshd5f0d4d4bf foreign key (id_wallet) references wallet;
alter table if exists income add constraint FK4fvq24jt4ybfm9tef5dpf2rwg foreign key (id_user) references usr;
alter table if exists income add constraint FKh3ov9r7o7y4mcluxfu4bksh3y foreign key (id_wallet) references wallet;
alter table if exists wallet add constraint FKgohu7dk0tk07p4b9ivtt7aqi5 foreign key (id_user_collaborator) references usr;
alter table if exists wallet add constraint FKcjfakv86qcbhwvbfs0dm65ryy foreign key (id_user_owner) references usr;
create table expense (id uuid not null, time_creation timestamp(6), time_removed timestamp(6), time_update timestamp(6), amount numeric(8,2) not null, date_register date not null, description varchar(100) not null, buy_method varchar(255), id_user uuid not null, id_wallet uuid not null, primary key (id));
create table income (id uuid not null, time_creation timestamp(6), time_removed timestamp(6), time_update timestamp(6), amount numeric(8,2) not null, date_register date not null, description varchar(100) not null, id_user uuid not null, id_wallet uuid not null, primary key (id));
create table usr (id uuid not null, time_creation timestamp(6), time_removed timestamp(6), time_update timestamp(6), email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id));
create table wallet (id uuid not null, time_creation timestamp(6), time_removed timestamp(6), time_update timestamp(6), month smallint not null, year integer not null, id_user_collaborator uuid, id_user_owner uuid not null, primary key (id));
alter table if exists usr add constraint UK_g9l96r670qkidthshajdtxrqf unique (email);
alter table if exists expense add constraint FKobusl0kfbkmsgeg2orbvlkyg4 foreign key (id_user) references usr;
alter table if exists expense add constraint FKcl45ciwbawegqshd5f0d4d4bf foreign key (id_wallet) references wallet;
alter table if exists income add constraint FK4fvq24jt4ybfm9tef5dpf2rwg foreign key (id_user) references usr;
alter table if exists income add constraint FKh3ov9r7o7y4mcluxfu4bksh3y foreign key (id_wallet) references wallet;
alter table if exists wallet add constraint FKgohu7dk0tk07p4b9ivtt7aqi5 foreign key (id_user_collaborator) references usr;
alter table if exists wallet add constraint FKcjfakv86qcbhwvbfs0dm65ryy foreign key (id_user_owner) references usr;
create table expense (id uuid not null, time_creation timestamp(6), time_removed timestamp(6), time_update timestamp(6), amount numeric(8,2) not null, date_register date not null, description varchar(100) not null, buy_method varchar(255), id_user uuid not null, id_wallet uuid not null, primary key (id));
create table income (id uuid not null, time_creation timestamp(6), time_removed timestamp(6), time_update timestamp(6), amount numeric(8,2) not null, date_register date not null, description varchar(100) not null, id_user uuid not null, id_wallet uuid not null, primary key (id));
create table usr (id uuid not null, time_creation timestamp(6), time_removed timestamp(6), time_update timestamp(6), email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id));
create table wallet (id uuid not null, time_creation timestamp(6), time_removed timestamp(6), time_update timestamp(6), month smallint not null, year integer not null, id_user_collaborator uuid, id_user_owner uuid not null, primary key (id));
alter table if exists usr add constraint UK_g9l96r670qkidthshajdtxrqf unique (email);
alter table if exists expense add constraint FKobusl0kfbkmsgeg2orbvlkyg4 foreign key (id_user) references usr;
alter table if exists expense add constraint FKcl45ciwbawegqshd5f0d4d4bf foreign key (id_wallet) references wallet;
alter table if exists income add constraint FK4fvq24jt4ybfm9tef5dpf2rwg foreign key (id_user) references usr;
alter table if exists income add constraint FKh3ov9r7o7y4mcluxfu4bksh3y foreign key (id_wallet) references wallet;
alter table if exists wallet add constraint FKgohu7dk0tk07p4b9ivtt7aqi5 foreign key (id_user_collaborator) references usr;
alter table if exists wallet add constraint FKcjfakv86qcbhwvbfs0dm65ryy foreign key (id_user_owner) references usr;
