version: '3.1'

services:

  financial-control-db:
    image: postgres
    container_name: financial_control
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_USER: financial_control
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"