spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financial_control
    username: financial_control
    password: admin
security:
  jwt:
    secret-key: jnxGXm9gdrWKPcFJfFVk7UODJbmZ0LZ1B5y7mFocT+o=
    expiration-time: 3600000